/* Main.c file generated by New Project wizard
 *
 * Created:   dj. oct. 27 2016
 * Processor: PIC18F4450
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#define _XTAL_FREQ 8000000
#include <stdlib.h> 
#include <string.h> 
#include <stdio.h>
#include "config.h"
#include "GLCD.h"
#include "ascii.h"
//#include "Bart.h"
#include "building.h"
//#include "car.h"
//#include "Picasso.h"
// Encen el pixel (x,y) del GLCD   x [0:63] y [0:127]
void SetDot(byte x, byte y) { 
   byte pagina = x/8; //64 pixels/8 pagines
   byte aux = readByte(pagina,y); //
   writeByte(pagina,y, aux | 1 << x%8);
}

// Apaga el pixel (x,y) del GLCD   x [0:63] y [0:127]
void ClearDot(byte x, byte y) { 
    byte pagina = x >> 3; // dividir entre 8
    byte aux = readByte(pagina, y);
    writeByte(pagina, y, aux & (1 << x%8));
}

void mouPunt(){ 
   int ri = 0;
   int re = 63;
   int ci = 0;
   int ce = 127;
   int i, j;
   for (i = ri; i <= re; i++) {
       for (j=ci;j<=ce;j++) {
	   SetDot(i,j); // pixel [i,j] del LCD a 1
	   __delay_ms(1);
	   ClearDot(i,j);
       }
   }
}

// Escriu el caracter c en la posicio (x,y) (x= 0 a 7) (y= 0 a 20)
// Els caracters estan definits en la taula font5x7[] 
void Putch(byte page, byte y, char c) { 
    int x = (c-32)*5; //comença per 32 i cadascun es codifica amb 5 posicions
    int i;
    for(i = 0; i < 5; ++i){
        writeByte(page, y + i,font5x7[x+i]);
    }
} 

// Escriu un text o string (s apunta al primer caracter del string) començant a la posicio (x,y) del GLCD 
//   (x= 0 a 7) (y= 0 a 20)

void writeTxt(byte page, byte y, char * text) {
    int i;
    int x = strlen(text);
    for (i = 0; i < x; ++i){
        Putch(page, y+(i*5), text[i]);
    }
}

// Escriu el nombre enter i en la posicio (page,y) (page= 0 a 7) (y= 0 a 20)
// Cal fer la conversió de SIGNED INTEGER to ASCII 
// Els caracters estan definits en la taula font5x7[] 
void writeNum(byte page, byte y, int i) {
    char buff[10];
    itoa (buff, i, 10);
    writeTxt(page, y, buff); 
 }
 
 void practica(){ 
   char buffer[256];
    sprintf(buffer,"Raul i Jose Luis");
    writeTxt(0,0,&buffer[0]);
    sprintf(buffer,"Grup: 13b");
    writeTxt(1,0,&buffer[0]);
    sprintf(buffer,"29/10/2016");
    writeTxt(2,0,&buffer[0]);
}

void imatge(){
    int i = 0;
    for(int page=0; page < 8; ++page){
        for(int y=0; y < 128; ++y){
	    writeByte(page,y,bitmap[i++]);
        }
    }
}

void main(void)
{
    ADCON1 = 0x0F;
    TRISD = 0x00;
    TRISB = 0x00;
    GLCDinit();
    clearGLCD(0, 7, 0, 127);
    setStartLine(0);
    //Putch(1,8,'a');
    //writeTxt(2,12,"Missatge de prova");
    //writeNum(2,12,45);
    imatge();
    //practica();
    //mouPunt();
    while (1);
}
